GET http://localhost:3000/product
Content-Type: application/json

{
  "id": "prod1"
}

### 
POST http://localhost:3000/product
Content-Type: application/json

{
  "product": {
    "name": "Morning",
    "price": 700,
    "description": "Best bottle out there",
    "stock": 2,
    "category": "Bottle"
  }
}

###
PUT http://localhost:3000/product
Content-Type: application/json

{
  "product": {
    "id": "prod1",
    "name": "Laptop",
    "price": 150,
    "description": "High-performance laptop",
    "stock": 10,
    "category": "Electronics"
  }

}

###
DELETE http://localhost:3000/product
Content-Type: application/json

{
  "id": "prod4"
}